#for default install all prerequisite


- name: Install Git
  become: True
  apt:
    name: git
    state: present
    update_cache: yes

- name: Install docker packages
  become: True
  apt:
    name: name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common']
    state: present
    update_cache: yes

- name: Add Docker s GPG key for ubuntu from official site
    become: True
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

- name: Verify gpg key with the fingerprint
  become: True
  apt_key:
    id: 0EBFCD88
    state: present

- name: Configure Docker for ubuntu stable repository
  become: True
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes

- name: Update apt packages
  become: True
  apt:
    update_cache: yes

- name: Install docker-ce
  become: True
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Install docker-compose from official github repo
  become: True
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0777